name: zigcc ci

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'zigcc/**/*.py'
  push:
    branches:
      - main
    paths:
      - 'zigcc/**/*.py'

defaults:
  run:
    working-directory: zigcc

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          pip install hatch
          pip install ruff
      - name: lint
        run: |
          make lint
